export default {
    CATEGORY: 'CATEGORY',
    CATEGORY_ADD: 'CATEGORY_ADD',
    ITEM: 'ITEM',
    ITEM_ADD: 'ITEM_ADD',
    ITEM_UPDATE: 'ITEM_UPDATE',
    LOGIN: 'LOGIN,',
    PROFILE: 'PROFILE',
    USER_MANAGEMENT: 'USER_MANAGEMENT',
}
